/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/logston/k8s-catzzz-logger/pkg/apis/catzzzlogger/v1"
	scheme "github.com/logston/k8s-catzzz-logger/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CatzzzLoggersGetter has a method to return a CatzzzLoggerInterface.
// A group's client should implement this interface.
type CatzzzLoggersGetter interface {
	CatzzzLoggers(namespace string) CatzzzLoggerInterface
}

// CatzzzLoggerInterface has methods to work with CatzzzLogger resources.
type CatzzzLoggerInterface interface {
	Create(ctx context.Context, catzzzLogger *v1.CatzzzLogger, opts metav1.CreateOptions) (*v1.CatzzzLogger, error)
	Update(ctx context.Context, catzzzLogger *v1.CatzzzLogger, opts metav1.UpdateOptions) (*v1.CatzzzLogger, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.CatzzzLogger, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CatzzzLoggerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CatzzzLogger, err error)
	CatzzzLoggerExpansion
}

// catzzzLoggers implements CatzzzLoggerInterface
type catzzzLoggers struct {
	client rest.Interface
	ns     string
}

// newCatzzzLoggers returns a CatzzzLoggers
func newCatzzzLoggers(c *PaullogstonV1Client, namespace string) *catzzzLoggers {
	return &catzzzLoggers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the catzzzLogger, and returns the corresponding catzzzLogger object, and an error if there is any.
func (c *catzzzLoggers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CatzzzLogger, err error) {
	result = &v1.CatzzzLogger{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("catzzzloggers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CatzzzLoggers that match those selectors.
func (c *catzzzLoggers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CatzzzLoggerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CatzzzLoggerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("catzzzloggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested catzzzLoggers.
func (c *catzzzLoggers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("catzzzloggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a catzzzLogger and creates it.  Returns the server's representation of the catzzzLogger, and an error, if there is any.
func (c *catzzzLoggers) Create(ctx context.Context, catzzzLogger *v1.CatzzzLogger, opts metav1.CreateOptions) (result *v1.CatzzzLogger, err error) {
	result = &v1.CatzzzLogger{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("catzzzloggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(catzzzLogger).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a catzzzLogger and updates it. Returns the server's representation of the catzzzLogger, and an error, if there is any.
func (c *catzzzLoggers) Update(ctx context.Context, catzzzLogger *v1.CatzzzLogger, opts metav1.UpdateOptions) (result *v1.CatzzzLogger, err error) {
	result = &v1.CatzzzLogger{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("catzzzloggers").
		Name(catzzzLogger.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(catzzzLogger).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the catzzzLogger and deletes it. Returns an error if one occurs.
func (c *catzzzLoggers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("catzzzloggers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *catzzzLoggers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("catzzzloggers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched catzzzLogger.
func (c *catzzzLoggers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CatzzzLogger, err error) {
	result = &v1.CatzzzLogger{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("catzzzloggers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
