/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	catzzzloggerv1 "github.com/logston/k8s-catzzz-logger/pkg/apis/catzzzlogger/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCatzzzLoggers implements CatzzzLoggerInterface
type FakeCatzzzLoggers struct {
	Fake *FakePaullogstonV1
	ns   string
}

var catzzzloggersResource = schema.GroupVersionResource{Group: "paullogston.com", Version: "v1", Resource: "catzzzloggers"}

var catzzzloggersKind = schema.GroupVersionKind{Group: "paullogston.com", Version: "v1", Kind: "CatzzzLogger"}

// Get takes name of the catzzzLogger, and returns the corresponding catzzzLogger object, and an error if there is any.
func (c *FakeCatzzzLoggers) Get(ctx context.Context, name string, options v1.GetOptions) (result *catzzzloggerv1.CatzzzLogger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(catzzzloggersResource, c.ns, name), &catzzzloggerv1.CatzzzLogger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*catzzzloggerv1.CatzzzLogger), err
}

// List takes label and field selectors, and returns the list of CatzzzLoggers that match those selectors.
func (c *FakeCatzzzLoggers) List(ctx context.Context, opts v1.ListOptions) (result *catzzzloggerv1.CatzzzLoggerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(catzzzloggersResource, catzzzloggersKind, c.ns, opts), &catzzzloggerv1.CatzzzLoggerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &catzzzloggerv1.CatzzzLoggerList{ListMeta: obj.(*catzzzloggerv1.CatzzzLoggerList).ListMeta}
	for _, item := range obj.(*catzzzloggerv1.CatzzzLoggerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested catzzzLoggers.
func (c *FakeCatzzzLoggers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(catzzzloggersResource, c.ns, opts))

}

// Create takes the representation of a catzzzLogger and creates it.  Returns the server's representation of the catzzzLogger, and an error, if there is any.
func (c *FakeCatzzzLoggers) Create(ctx context.Context, catzzzLogger *catzzzloggerv1.CatzzzLogger, opts v1.CreateOptions) (result *catzzzloggerv1.CatzzzLogger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(catzzzloggersResource, c.ns, catzzzLogger), &catzzzloggerv1.CatzzzLogger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*catzzzloggerv1.CatzzzLogger), err
}

// Update takes the representation of a catzzzLogger and updates it. Returns the server's representation of the catzzzLogger, and an error, if there is any.
func (c *FakeCatzzzLoggers) Update(ctx context.Context, catzzzLogger *catzzzloggerv1.CatzzzLogger, opts v1.UpdateOptions) (result *catzzzloggerv1.CatzzzLogger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(catzzzloggersResource, c.ns, catzzzLogger), &catzzzloggerv1.CatzzzLogger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*catzzzloggerv1.CatzzzLogger), err
}

// Delete takes name of the catzzzLogger and deletes it. Returns an error if one occurs.
func (c *FakeCatzzzLoggers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(catzzzloggersResource, c.ns, name), &catzzzloggerv1.CatzzzLogger{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCatzzzLoggers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(catzzzloggersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &catzzzloggerv1.CatzzzLoggerList{})
	return err
}

// Patch applies the patch and returns the patched catzzzLogger.
func (c *FakeCatzzzLoggers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *catzzzloggerv1.CatzzzLogger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(catzzzloggersResource, c.ns, name, pt, data, subresources...), &catzzzloggerv1.CatzzzLogger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*catzzzloggerv1.CatzzzLogger), err
}
